-- MySQL Script generated by MySQL Workbench
-- Mon Oct  2 18:03:48 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET utf8 ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`Administration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`Administration` ;

CREATE TABLE IF NOT EXISTS `hospital`.`Administration` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `salaryRate` INT NOT NULL,
  `personalRoom` TINYINT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `idAdministration_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Medical`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`Medical` ;

CREATE TABLE IF NOT EXISTS `hospital`.`Medical` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `specialization` TINYINT NOT NULL,
  `nightShift` TINYINT NOT NULL,
  `medicalExp` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `idMedical_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`Address` ;

CREATE TABLE IF NOT EXISTS `hospital`.`Address` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `houseNumber` INT NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `cities` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `idAddress_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`HospitalStaff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`HospitalStaff` ;

CREATE TABLE IF NOT EXISTS `hospital`.`HospitalStaff` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `jobTitle` VARCHAR(45) NOT NULL,
  `address` INT NOT NULL,
  `dateBirth` DATETIME NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Medical_ID` INT UNSIGNED NOT NULL,
  `GeneralPractice_ID` INT UNSIGNED NOT NULL,
  `Address_ID` INT UNSIGNED NOT NULL,
  `Administration_ID` INT UNSIGNED NOT NULL,
  `ChiefAccountant_ID` INT UNSIGNED NOT NULL,
  `ChiefMedical_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_HospitalStaff_Administration1_idx` (`Administration_ID` ASC, `ChiefAccountant_ID` ASC, `ChiefMedical_ID` ASC),
  INDEX `fk_HospitalStaff_Medical1_idx` (`Medical_ID` ASC, `GeneralPractice_ID` ASC),
  UNIQUE INDEX `idHospitalStaff_UNIQUE` (`ID` ASC),
  INDEX `fk_HospitalStaff_Address1_idx` (`Address_ID` ASC),
  CONSTRAINT `fk_HospitalStaff_Administration1`
    FOREIGN KEY (`Administration_ID`)
    REFERENCES `hospital`.`Administration` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HospitalStaff_Medical1`
    FOREIGN KEY (`Medical_ID`)
    REFERENCES `hospital`.`Medical` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HospitalStaff_Address1`
    FOREIGN KEY (`Address_ID`)
    REFERENCES `hospital`.`Address` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Support`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`Support` ;

CREATE TABLE IF NOT EXISTS `hospital`.`Support` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `relatedEducation` TINYINT(1) NOT NULL,
  `privileges` TINYINT(1) NOT NULL,
  `HospitalStaff_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `idSupport_UNIQUE` (`ID` ASC),
  INDEX `fk_Support_HospitalStaff1_idx` (`HospitalStaff_ID` ASC),
  CONSTRAINT `fk_Support_HospitalStaff1`
    FOREIGN KEY (`HospitalStaff_ID`)
    REFERENCES `hospital`.`HospitalStaff` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`ChiefAccountant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`ChiefAccountant` ;

CREATE TABLE IF NOT EXISTS `hospital`.`ChiefAccountant` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `economicEducation` TINYINT NOT NULL,
  `Administration_ID` INT UNSIGNED NOT NULL,
  `ChiefAccountant_ID` INT UNSIGNED NOT NULL,
  `ChiefMedical_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ChiefAccountant_Administration1_idx` (`Administration_ID` ASC, `ChiefAccountant_ID` ASC, `ChiefMedical_ID` ASC),
  UNIQUE INDEX `idChiefAccountant_UNIQUE` (`ID` ASC),
  CONSTRAINT `fk_ChiefAccountant_Administration1`
    FOREIGN KEY (`Administration_ID`)
    REFERENCES `hospital`.`Administration` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`ChiefMedical`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`ChiefMedical` ;

CREATE TABLE IF NOT EXISTS `hospital`.`ChiefMedical` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phD` TINYINT(1) NOT NULL,
  `awards` VARCHAR(45) NOT NULL,
  `Administration_ID` INT UNSIGNED NOT NULL,
  `ChiefAccountant_ID` INT UNSIGNED NOT NULL,
  `ChiefMedical_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ChiefMedical_Administration1_idx` (`Administration_ID` ASC, `ChiefAccountant_ID` ASC, `ChiefMedical_ID` ASC),
  UNIQUE INDEX `idChiefMedical_UNIQUE` (`ID` ASC),
  CONSTRAINT `fk_ChiefMedical_Administration1`
    FOREIGN KEY (`Administration_ID`)
    REFERENCES `hospital`.`Administration` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`GeneralPractice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`GeneralPractice` ;

CREATE TABLE IF NOT EXISTS `hospital`.`GeneralPractice` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `surgicalPractice` TINYINT(1) NOT NULL,
  `Medical_ID` INT UNSIGNED NOT NULL,
  `GeneralPractice_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_GeneralPractice_Medical1_idx` (`Medical_ID` ASC, `GeneralPractice_ID` ASC),
  UNIQUE INDEX `idGeneralPractice_UNIQUE` (`ID` ASC),
  CONSTRAINT `fk_GeneralPractice_Medical1`
    FOREIGN KEY (`Medical_ID`)
    REFERENCES `hospital`.`Medical` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`Driver` ;

CREATE TABLE IF NOT EXISTS `hospital`.`Driver` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `drivingExp` TINYINT(1) NOT NULL,
  `Support_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `idDriver_UNIQUE` (`ID` ASC),
  INDEX `fk_Driver_Support1_idx` (`Support_ID` ASC),
  CONSTRAINT `fk_Driver_Support1`
    FOREIGN KEY (`Support_ID`)
    REFERENCES `hospital`.`Support` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Janitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`Janitor` ;

CREATE TABLE IF NOT EXISTS `hospital`.`Janitor` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `useInstruments` TINYINT(1) NOT NULL,
  `Support_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `idJanitor_UNIQUE` (`ID` ASC),
  INDEX `fk_Janitor_Support1_idx` (`Support_ID` ASC),
  CONSTRAINT `fk_Janitor_Support1`
    FOREIGN KEY (`Support_ID`)
    REFERENCES `hospital`.`Support` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
