-- MySQL Script generated by MySQL Workbench
-- Thu Sep 28 20:30:25 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET utf8 ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`Administration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Administration` (
  `idAdministration` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `salaryRate` INT NOT NULL,
  `personalRoom` TINYINT NULL,
  `ChiefAccountant_idChiefAccountant` INT NOT NULL,
  `ChiefMedical_idChiefMedical` INT NOT NULL,
  PRIMARY KEY (`idAdministration`, `ChiefAccountant_idChiefAccountant`, `ChiefMedical_idChiefMedical`),
  UNIQUE INDEX `idAdministration_UNIQUE` (`idAdministration` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Medical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Medical` (
  `idMedical` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `specialization` TINYINT(1) NULL,
  `nightShift` TINYINT(1) NULL,
  `medicalExp` INT NOT NULL,
  `GeneralPractice_idGeneralPractice` INT NOT NULL,
  PRIMARY KEY (`idMedical`, `GeneralPractice_idGeneralPractice`),
  UNIQUE INDEX `idMedical_UNIQUE` (`idMedical` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Address` (
  `idAddress` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `houseNumber` INT NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `cities` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAddress`),
  UNIQUE INDEX `idAddress_UNIQUE` (`idAddress` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`HospitalStaff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`HospitalStaff` (
  `idHospitalStaff` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `jobTitle` VARCHAR(45) NOT NULL,
  `address` INT NOT NULL,
  `dateBirth` DATETIME NOT NULL,
  `Administration_idAdministration` INT UNSIGNED NOT NULL,
  `Administration_ChiefAccountant_idChiefAccountant` INT UNSIGNED NOT NULL,
  `Administration_ChiefMedical_idChiefMedical` INT UNSIGNED NOT NULL,
  `Medical_idMedical` INT UNSIGNED NOT NULL,
  `Medical_GeneralPractice_idGeneralPractice` INT UNSIGNED NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Address_idAddress` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idHospitalStaff`),
  INDEX `fk_HospitalStaff_Administration1_idx` (`Administration_idAdministration` ASC, `Administration_ChiefAccountant_idChiefAccountant` ASC, `Administration_ChiefMedical_idChiefMedical` ASC),
  INDEX `fk_HospitalStaff_Medical1_idx` (`Medical_idMedical` ASC, `Medical_GeneralPractice_idGeneralPractice` ASC),
  UNIQUE INDEX `idHospitalStaff_UNIQUE` (`idHospitalStaff` ASC),
  INDEX `fk_HospitalStaff_Address1_idx` (`Address_idAddress` ASC),
  CONSTRAINT `fk_HospitalStaff_Administration1`
    FOREIGN KEY (`Administration_idAdministration` , `Administration_ChiefAccountant_idChiefAccountant` , `Administration_ChiefMedical_idChiefMedical`)
    REFERENCES `hospital`.`Administration` (`idAdministration` , `ChiefAccountant_idChiefAccountant` , `ChiefMedical_idChiefMedical`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HospitalStaff_Medical1`
    FOREIGN KEY (`Medical_idMedical` , `Medical_GeneralPractice_idGeneralPractice`)
    REFERENCES `hospital`.`Medical` (`idMedical` , `GeneralPractice_idGeneralPractice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HospitalStaff_Address1`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `hospital`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Support`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Support` (
  `idSupport` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `relatedEducation` TINYINT(1) NOT NULL,
  `privileges` TINYINT(1) NOT NULL,
  `HospitalStaff_idHospitalStaff` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idSupport`),
  UNIQUE INDEX `idSupport_UNIQUE` (`idSupport` ASC),
  INDEX `fk_Support_HospitalStaff1_idx` (`HospitalStaff_idHospitalStaff` ASC),
  CONSTRAINT `fk_Support_HospitalStaff1`
    FOREIGN KEY (`HospitalStaff_idHospitalStaff`)
    REFERENCES `hospital`.`HospitalStaff` (`idHospitalStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`ChiefAccountant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`ChiefAccountant` (
  `idChiefAccountant` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `economicEducation` TINYINT(1) NOT NULL,
  `Administration_idAdministration` INT NOT NULL,
  `Administration_ChiefAccountant_idChiefAccountant` INT NOT NULL,
  `Administration_ChiefMedical_idChiefMedical` INT NOT NULL,
  PRIMARY KEY (`idChiefAccountant`),
  INDEX `fk_ChiefAccountant_Administration1_idx` (`Administration_idAdministration` ASC, `Administration_ChiefAccountant_idChiefAccountant` ASC, `Administration_ChiefMedical_idChiefMedical` ASC),
  UNIQUE INDEX `idChiefAccountant_UNIQUE` (`idChiefAccountant` ASC),
  CONSTRAINT `fk_ChiefAccountant_Administration1`
    FOREIGN KEY (`Administration_idAdministration` , `Administration_ChiefAccountant_idChiefAccountant` , `Administration_ChiefMedical_idChiefMedical`)
    REFERENCES `hospital`.`Administration` (`idAdministration` , `ChiefAccountant_idChiefAccountant` , `ChiefMedical_idChiefMedical`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`ChiefMedical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`ChiefMedical` (
  `idChiefMedical` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phD` TINYINT(1) NOT NULL,
  `awards` VARCHAR(45) NULL,
  `Administration_idAdministration` INT NOT NULL,
  `Administration_ChiefAccountant_idChiefAccountant` INT NOT NULL,
  `Administration_ChiefMedical_idChiefMedical` INT NOT NULL,
  PRIMARY KEY (`idChiefMedical`),
  INDEX `fk_ChiefMedical_Administration1_idx` (`Administration_idAdministration` ASC, `Administration_ChiefAccountant_idChiefAccountant` ASC, `Administration_ChiefMedical_idChiefMedical` ASC),
  UNIQUE INDEX `idChiefMedical_UNIQUE` (`idChiefMedical` ASC),
  CONSTRAINT `fk_ChiefMedical_Administration1`
    FOREIGN KEY (`Administration_idAdministration` , `Administration_ChiefAccountant_idChiefAccountant` , `Administration_ChiefMedical_idChiefMedical`)
    REFERENCES `hospital`.`Administration` (`idAdministration` , `ChiefAccountant_idChiefAccountant` , `ChiefMedical_idChiefMedical`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`GeneralPractice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`GeneralPractice` (
  `idGeneralPractice` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `surgicalPractice` TINYINT(1) NOT NULL,
  `Medical_idMedical` INT NOT NULL,
  `Medical_GeneralPractice_idGeneralPractice` INT NOT NULL,
  PRIMARY KEY (`idGeneralPractice`),
  INDEX `fk_GeneralPractice_Medical1_idx` (`Medical_idMedical` ASC, `Medical_GeneralPractice_idGeneralPractice` ASC),
  UNIQUE INDEX `idGeneralPractice_UNIQUE` (`idGeneralPractice` ASC),
  CONSTRAINT `fk_GeneralPractice_Medical1`
    FOREIGN KEY (`Medical_idMedical` , `Medical_GeneralPractice_idGeneralPractice`)
    REFERENCES `hospital`.`Medical` (`idMedical` , `GeneralPractice_idGeneralPractice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Driver` (
  `idDriver` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `drivingExp` TINYINT(1) NOT NULL,
  `Support_idSupport` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idDriver`),
  UNIQUE INDEX `idDriver_UNIQUE` (`idDriver` ASC),
  INDEX `fk_Driver_Support1_idx` (`Support_idSupport` ASC),
  CONSTRAINT `fk_Driver_Support1`
    FOREIGN KEY (`Support_idSupport`)
    REFERENCES `hospital`.`Support` (`idSupport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Janitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Janitor` (
  `idJanitor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `useInstruments` TINYINT(1) NOT NULL,
  `Support_idSupport` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idJanitor`),
  UNIQUE INDEX `idJanitor_UNIQUE` (`idJanitor` ASC),
  INDEX `fk_Janitor_Support1_idx` (`Support_idSupport` ASC),
  CONSTRAINT `fk_Janitor_Support1`
    FOREIGN KEY (`Support_idSupport`)
    REFERENCES `hospital`.`Support` (`idSupport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `hospital` ;

-- -----------------------------------------------------
-- Placeholder table for view `hospital`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`view1` (`id` INT);

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `hospital`$$
$$

DELIMITER ;

-- -----------------------------------------------------
-- View `hospital`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`view1`;
USE `hospital`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
