-- MySQL Script generated by MySQL Workbench
-- Mon Sep 25 00:35:51 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET utf8 ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `houseNumber` INT NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `cities` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAddress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Driver` (
  `idDriver` INT NOT NULL AUTO_INCREMENT,
  `drivingExp` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idDriver`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Janitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Janitor` (
  `idJanitor` INT NOT NULL AUTO_INCREMENT,
  `useInstruments` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idJanitor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Support`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Support` (
  `idSupport` INT NOT NULL AUTO_INCREMENT,
  `relatedEducation` TINYINT(1) NOT NULL,
  `privileges` TINYINT(1) NOT NULL,
  `Driver_idDriver` INT NOT NULL,
  `Janitor_idJanitor` INT NOT NULL,
  PRIMARY KEY (`idSupport`, `Driver_idDriver`, `Janitor_idJanitor`),
  INDEX `fk_Support_Driver1_idx` (`Driver_idDriver` ASC),
  INDEX `fk_Support_Janitor1_idx` (`Janitor_idJanitor` ASC),
  CONSTRAINT `fk_Support_Driver1`
    FOREIGN KEY (`Driver_idDriver`)
    REFERENCES `hospital`.`Driver` (`idDriver`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Support_Janitor1`
    FOREIGN KEY (`Janitor_idJanitor`)
    REFERENCES `hospital`.`Janitor` (`idJanitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`ChiefAccountant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`ChiefAccountant` (
  `idChiefAccountant` INT NOT NULL AUTO_INCREMENT,
  `economicEducation` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idChiefAccountant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`ChiefMedical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`ChiefMedical` (
  `idChiefMedical` INT NOT NULL AUTO_INCREMENT,
  `phD` TINYINT(1) NOT NULL,
  `awards` VARCHAR(45) NULL,
  PRIMARY KEY (`idChiefMedical`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Administration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Administration` (
  `idAdministration` INT NOT NULL AUTO_INCREMENT,
  `salaryRate` INT NOT NULL,
  `personalRoom` TINYINT NULL,
  `ChiefAccountant_idChiefAccountant` INT NOT NULL,
  `ChiefMedical_idChiefMedical` INT NOT NULL,
  PRIMARY KEY (`idAdministration`, `ChiefAccountant_idChiefAccountant`, `ChiefMedical_idChiefMedical`),
  INDEX `fk_Administration_ChiefAccountant1_idx` (`ChiefAccountant_idChiefAccountant` ASC),
  INDEX `fk_Administration_ChiefMedical1_idx` (`ChiefMedical_idChiefMedical` ASC),
  CONSTRAINT `fk_Administration_ChiefAccountant1`
    FOREIGN KEY (`ChiefAccountant_idChiefAccountant`)
    REFERENCES `hospital`.`ChiefAccountant` (`idChiefAccountant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Administration_ChiefMedical1`
    FOREIGN KEY (`ChiefMedical_idChiefMedical`)
    REFERENCES `hospital`.`ChiefMedical` (`idChiefMedical`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`MedicalEmployees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`MedicalEmployees` (
  `idMedicalEmployees` INT NOT NULL AUTO_INCREMENT,
  `specialization` VARCHAR(45) NOT NULL,
  `nightShift` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idMedicalEmployees`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`HospitalStaff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`HospitalStaff` (
  `idHospitalStaff` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `jobTitle` VARCHAR(45) NOT NULL,
  `address` BLOB NOT NULL,
  `dateBirth` DATETIME NOT NULL,
  `Address_idAddress` INT NOT NULL,
  `Support_idSupport` INT NOT NULL,
  `Administration_idAdministration` INT NOT NULL,
  `MedicalEmployees_idMedicalEmployees` INT NOT NULL,
  PRIMARY KEY (`idHospitalStaff`, `Address_idAddress`, `Support_idSupport`, `Administration_idAdministration`, `MedicalEmployees_idMedicalEmployees`),
  INDEX `fk_HospitalStaff_Address_idx` (`Address_idAddress` ASC),
  INDEX `fk_HospitalStaff_Support1_idx` (`Support_idSupport` ASC),
  INDEX `fk_HospitalStaff_Administration1_idx` (`Administration_idAdministration` ASC),
  INDEX `fk_HospitalStaff_MedicalEmployees1_idx` (`MedicalEmployees_idMedicalEmployees` ASC),
  CONSTRAINT `fk_HospitalStaff_Address`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `hospital`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HospitalStaff_Support1`
    FOREIGN KEY (`Support_idSupport`)
    REFERENCES `hospital`.`Support` (`idSupport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HospitalStaff_Administration1`
    FOREIGN KEY (`Administration_idAdministration`)
    REFERENCES `hospital`.`Administration` (`idAdministration`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HospitalStaff_MedicalEmployees1`
    FOREIGN KEY (`MedicalEmployees_idMedicalEmployees`)
    REFERENCES `hospital`.`MedicalEmployees` (`idMedicalEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`GeneralPractice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`GeneralPractice` (
  `idGeneralPractice` INT NOT NULL AUTO_INCREMENT,
  `surgicalPractice` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idGeneralPractice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Medical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Medical` (
  `idMedical` INT NOT NULL AUTO_INCREMENT,
  `specialization` TINYINT(1) NULL,
  `nightShift` TINYINT(1) NULL,
  `medicalExp` INT NOT NULL,
  `GeneralPractice_idGeneralPractice` INT NOT NULL,
  PRIMARY KEY (`idMedical`, `GeneralPractice_idGeneralPractice`),
  INDEX `fk_Medical_GeneralPractice1_idx` (`GeneralPractice_idGeneralPractice` ASC),
  CONSTRAINT `fk_Medical_GeneralPractice1`
    FOREIGN KEY (`GeneralPractice_idGeneralPractice`)
    REFERENCES `hospital`.`GeneralPractice` (`idGeneralPractice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `hospital` ;

-- -----------------------------------------------------
-- Placeholder table for view `hospital`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`view1` (`id` INT);

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `hospital`$$
$$

DELIMITER ;

-- -----------------------------------------------------
-- View `hospital`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`view1`;
USE `hospital`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Address (houseNumber,phone,street,cities) VALUES ('5', '+375298916671','Lenina','MINSK');
INSERT INTO Address (houseNumber,phone,street,cities) VALUES ('6', '+375298916672','Komsomolskaya','BORISOV');
INSERT INTO Address (houseNumber,phone,street,cities) VALUES ('7', '+375298916673','Minina','CHERVEN');
INSERT INTO Address (houseNumber,phone,street,cities) VALUES ('8', '+375298916674','Frunze','FANIPOL');
INSERT INTO Address (houseNumber,phone,street,cities) VALUES ('9', '+375298916675','Mayakovskaya','DZERZHINSK');
INSERT INTO Address (houseNumber,phone,street,cities) VALUES ('10', '+375298916676','Solnechnaya','KLETSK');
INSERT INTO Address (houseNumber,phone,street,cities) VALUES ('11', '+375298916677','Fabrichnaya','KOPYL');

INSERT INTO ChiefMedical (phD,awards) VALUES ('1','2');
INSERT INTO ChiefMedical (phD,awards) VALUES ('1','2');

INSERT INTO ChiefAccountant