package com.qaprosoft.hospital.models;

public enum Cities {
	BORISOV, CHERVEN, DZERZHINSK, FANIPOL, KLETSK, KOPYL, KRYPKI, LOGOYSK, LYUBAN, MARINAGORKA, 
	MINSK, MOLODECHNO, MYADEL, NESVIZH, SLUTSK, SMOLEVICHI, SOLIGORSK, STARYYEDOROGI, STOLBTSY, UZDA, VILEYKA, VOLOZHIN, ZASLAV, ZHODINO
}
